const Constants = {
  type: "AGENT",
  //wsUrl: "https://app.mnc-insurance.com/wsmnciers/webservice.asmx?wsdl",
  wsUrl: "https://uat-app.mnc-insurance.com/wsmnciagent/webservice.asmx?wsdl",
  wsLogin: "Login",
  wsPremiumProduction: "PremiumProduction",
  wsExpiryPolicyGroup: "ExpiryPolicyGroup",
  wsExpiryPolicy: "ExpiryPolicy",
  wsOutstandingPremium: "OutstandingPremium",
  wsOutstandingPremiumDetail: "OutstandingPremiumDetail",
  wsClaimInfo: "ClaimInfo",
  wsLicenseCheckExist: "LicenseCheckExist",
  wsSearchPolicy: "SearchPolicy",
  wsBranch: "Branch",
  wsWorkshop: "Workshop",
  wsFirstReportClaim: "FirstReportClaim",
  wsEventSchedule: "EventSchedule",
  wsGetVehicle: "GetVehicle",
  wsPremiumCalculation: "PremiumCalculation",
  wsAddQuotation: "AddQuotation",
  wsGetQuotation: "GetQuotation",
  wsUploadImage: "UploadImage",
  wsForgotPassword: "ForgotPassword",
  wsChangePassword: "ChangePassword",
  wsUpdateProfile: "UpdateProfile",
  wsGetNotifications: "GetNotifications",
  wsUpdateNotification: "UpdateNotification",
  wsCreateQuotationDocument: "CreateQuotationDocument",
  KEY_DATA_USER: "DATA_USER",
  KEY_USER_ID: "USER_ID",
  KEY_PASSWORD: "PASSWORD",
  KEY_DATA_LOGIN: "DATA_LOGIN"
};

export { Constants };
